sudo: required
services:
  - docker

before_install:
  - docker build -t padronlv/docker-react -f Dockerfile.dev .

script:
  - docker container run -e CI=true padronlv/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket-name: "elastic....name"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY